openapi: 3.0.3
info:
  title: Zedux API
  version: 1.0.0
  description: an online learning platform api
paths:
  /api/auth/login/:
    post:
      operationId: auth_login_create
      tags:
      - auth
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/auth/logout/:
    post:
      operationId: auth_logout_create
      tags:
      - auth
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/categories/:
    get:
      operationId: categories_retrieve
      tags:
      - categories
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: categories_create
      tags:
      - categories
      security:
      - jwtAuth: []
      responses:
        '201':
          description: No response body
  /api/categories/{id}/:
    get:
      operationId: categories_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - categories
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    put:
      operationId: categories_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - categories
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: categories_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - categories
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/course-materials/:
    get:
      operationId: course_materials_retrieve
      tags:
      - course-materials
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: course_materials_create
      tags:
      - course-materials
      security:
      - jwtAuth: []
      responses:
        '201':
          description: No response body
  /api/course-materials/{id}/:
    get:
      operationId: course_materials_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - course-materials
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    put:
      operationId: course_materials_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - course-materials
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: course_materials_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - course-materials
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/courses/:
    get:
      operationId: courses_retrieve
      tags:
      - courses
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: courses_create
      tags:
      - courses
      security:
      - jwtAuth: []
      responses:
        '201':
          description: No response body
  /api/courses/{id}/:
    get:
      operationId: courses_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - courses
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    put:
      operationId: courses_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - courses
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: courses_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - courses
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/instructors/:
    get:
      operationId: instructors_retrieve
      tags:
      - instructors
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: instructors_create
      tags:
      - instructors
      security:
      - jwtAuth: []
      responses:
        '201':
          description: No response body
  /api/instructors/{id}/:
    get:
      operationId: instructors_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - instructors
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    put:
      operationId: instructors_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - instructors
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: instructors_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - instructors
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/instructors/become_an_instructor/:
    post:
      operationId: instructors_become_an_instructor_create
      tags:
      - instructors
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/my-cart/:
    get:
      operationId: my_cart_retrieve
      tags:
      - my-cart
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/my-cart/{id}/:
    get:
      operationId: my_cart_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - my-cart
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: my_cart_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - my-cart
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/my-cart/add/{course_id}/:
    post:
      operationId: my_cart_add_create
      parameters:
      - in: path
        name: course_id
        schema:
          type: integer
        required: true
      tags:
      - my-cart
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/my-cart/add_to_cart/:
    post:
      operationId: my_cart_add_to_cart_create
      tags:
      - my-cart
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/my-course/:
    get:
      operationId: my_course_retrieve
      tags:
      - my-course
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/my-course/{id}/:
    get:
      operationId: my_course_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - my-course
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: my_course_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - my-course
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/my-course/add/{course_id}/:
    post:
      operationId: my_course_add_create
      parameters:
      - in: path
        name: course_id
        schema:
          type: integer
        required: true
      tags:
      - my-course
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/my-course/add_to_my_course/:
    post:
      operationId: my_course_add_to_my_course_create
      tags:
      - my-course
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/users/:
    get:
      operationId: users_retrieve
      tags:
      - users
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: users_create
      tags:
      - users
      security:
      - jwtAuth: []
      responses:
        '201':
          description: No response body
  /api/users/{id}/:
    get:
      operationId: users_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - users
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    put:
      operationId: users_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - users
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: users_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - users
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
components:
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
