# Generated by Django 5.1.2 on 2024-11-02 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='joined_at',
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 2, 13, 42, 27, 787786, tzinfo=datetime.timezone.utc)),
        ),
    ]
