# Generated by Django 5.1.2 on 2024-11-12 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 12, 9, 25, 51, 168907, tzinfo=datetime.timezone.utc)),
        ),
    ]
