# Generated by Django 5.1.2 on 2024-11-02 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_customuser_joined_at_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 2, 13, 51, 25, 643891, tzinfo=datetime.timezone.utc)),
        ),
    ]
