# Generated by Django 5.1.2 on 2024-10-23 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_coursematerial_text_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(8, 'password must not be less the 8')]),
        ),
    ]
