# Generated by Django 5.1.2 on 2024-11-13 09:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='certificate',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='course_certificate'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='other_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='others'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='video_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='course_video'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_picture'),
        ),
    ]
