# Generated by Django 5.1.2 on 2024-10-23 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_customuser_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_materials',
            new_name='course_material',
        ),
    ]
