# Generated by Django 5.1.2 on 2024-10-24 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_course_materials_course_course_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursematerial',
            old_name='others_file',
            new_name='other_file',
        ),
    ]
