# Generated by Django 5.1.2 on 2024-10-29 16:07

import base.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_coursematerial_text_file_alter_customuser_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid username', message='username must contain letters , numbers and underscores,@,and # only', regex='^[a-zA-Z0-9_@#]+$'), base.models.CustomUser.validate_username]),
        ),
    ]
